### ISSUE TITLE
Bug: There is no script to initialize the password

### ISSUE THREAD

**Issue by klniu** [openimsdk/openim-docker#1]
### What happened?

There is no script to initialize the password. On the official website, it is `install_im_server.sh`. If I want to do that, I need to copy `.env` to the open-server directory, and execute the `init_pwd.sh`.

Also, could you tell me where the env directory is mentioned in Readme?

### What did you expect to happen?

Provide a method to initialize the config

### How can we reproduce it (as minimally and precisely as possible)?

As above

### version

main repository

### Cloud provider

Ubuntu 20.04

### OS version

Ubuntu 20.04

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
You'll need to manually change the.env and config.yaml files in those directories

**Comment by cubxxw** [comment]
Automated tools are doing it

**Comment by klniu** [comment]
Thanks.

Additionally, the path mongodb initial script is not correct: 
```
./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
```
