### ISSUE TITLE
oss upload signature error [BUG]

### ISSUE THREAD

**Issue by hackerjmss** [openimsdk/openim-docker#157]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

我已经填写了 oss 信息，并且验证过信息确实是正确的，但是上传的时候提示签名错误
![WechatIMG31](https://github.com/user-attachments/assets/dbf28c82-27c1-4853-a6a6-efdddbb9e216)
![WechatIMG33](https://github.com/user-attachments/assets/976b2d1f-217f-41d0-bf34-a650eb5ddfec)

**Comment by coobaa** [comment]
需要配置nginx规则
参考：https://minio.org.cn/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
