### ISSUE TITLE
How to set up chat without adding friends？

### ISSUE THREAD

**Issue by Skx666** [openimsdk/openim-docker#164]
### What would you like to share?

![image](https://github.com/user-attachments/assets/2ba4663c-d85b-4f76-b486-d4c22a23983a)
I added IMENV_OPENIM_RPC_FRIEND_FRIENDVERIFY=true, saved it, and restarted the service, but it still doesn't work. In the 'Add Friend' interface, messages can still be sent directly, and the setting hasn't taken effect. I've tried multiple times, but the issue persists.

**Comment by Skx666** [comment]
![image](https://github.com/user-attachments/assets/9d875d5b-2dd3-43f4-ac29-0485fff05195)

**Comment by icey-yu** [comment]
I added IMENV_OPENIM_RPC_FRIEND_FRIENDVERIFY=true, saved it, and restarted the service, but it still doesn't work. In the 'Add Friend' interface, messages can still be sent directly, and the setting hasn't taken effect. I've tried multiple times, but the issue persists.

**Comment by icey-yu** [comment]
#162
