### ISSUE TITLE
[BUG]  The business server did not receive a callback request

### ISSUE THREAD

**Issue by ciooool** [openimsdk/openim-docker#178]
### OpenIM Server Version

release-v3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

Environment variables have been set in docker-compose.yaml, but the business server still cannot receive callback requests

### Screenshots Link

![42cf170495e6bccf9cb43632574f018](https://github.com/user-attachments/assets/9958c917-910b-4245-ac00-698355bc0b7a)
![66c0ecbb5d8d7d0b20940d3e162303a](https://github.com/user-attachments/assets/0aa91f2c-96ff-4925-bb6d-73362376c921)

**Comment by skiffer-git** [comment]
You don't need to modify the config file in the container; you just need to set the environment variables in the docker-compose.yaml file.

**Comment by skiffer-git** [comment]
If it doesn't work, you can check the logs related to the webhook.

**Comment by icey-yu** [comment]
You should change URL to `http://xxx:8090/callbackExample`
