### ISSUE TITLE
[FEATURE REQUEST] Write the open-im-server/config/openim-push.yml configuration to env

### ISSUE THREAD

**Issue by lincome** [openimsdk/openim-docker#181]
### Why this feature?

Convenient modification of push service

### Suggested Solution

Read env configuration first, so it won't be lost after restart

**Comment by icey-yu** [comment]
Please refer to the following for instructions on modifying the configuration files:
https://docs.openim.io/zh-Hans/guides/gettingStarted/dockerCompose
