### ISSUE TITLE
[BUG] When I use the API to register a new user, I get the error message "secret invalid: 1002 NoPermissionError."

### ISSUE THREAD

**Issue by weiwuxing** [openimsdk/openim-docker#185]
### OpenIM Server Version

最新版

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

先获取的管理员token,{
  "secret": "openIM123",
  "platformID": 10,(或1都试过)
  "userID": "imAdmin111"
},然后去注册的新用户。提示上面的问题。

### Screenshots Link

![WX20240926-144621](https://github.com/user-attachments/assets/4daea1a8-ae8d-4993-9b90-39797ae7ff86)

**Comment by skiffer-git** [comment]
"userID": "imAdmin111" should be imAdmin

**Comment by weiwuxing** [comment]
> "userID": "imAdmin111"

开始用的“imAdmin”，报的错误是一样的。你们用api注册用户可以成功吗

**Comment by icey-yu** [comment]
In the current version, you need to add a "secret" field in the JSON to make a request. After updating the Docker version, only an admin token will be required for registration, eliminating the need for a "secret".
