### ISSUE TITLE
can not access 11001 port

### ISSUE THREAD

**Issue by yipianchuyun** [openimsdk/openim-docker#203]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

can not access 11001 port
![error](https://github.com/user-attachments/assets/f28b977f-ac0c-491f-bcd4-3f97b9f2af38)

**Comment by icey-yu** [comment]
Could you confirm if the firewall is blocking access to this port?

**Comment by yipianchuyun** [comment]
> Could you confirm if the firewall is blocking access to this port?

but inside container, the server is not listening on port 11001
