### ISSUE TITLE
Bug: The openim-server log record could not be found

### ISSUE THREAD

**Issue by fx10007** [openimsdk/openim-docker#52]
### What happened?

The openim-server log record could not be found
The log inside the container can't be found

### What did you expect to happen?

The log information does not appear in the specified location

### How can we reproduce it (as minimally and precisely as possible)?

docker compose 一键部署
``` 
git clone https://github.com/openim-sigs/openim-docker openim/openim-docker && export openim=$(pwd)/openim && cd $openim/openim-docker && make init && docker compose up -d 
 ```

### version

openim-server: 3.4
openim-chat: 1.4

### Cloud provider

aliyun

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
Could you please enter the container of openim-server and navigate to the config/config.yaml file? Once you are inside the container, you will find the storageLocation path which corresponds to the log path.

Kindly modify this path to the correct location, for example, /openim/openim-server/logs/.
