### ISSUE TITLE
Bug: Cannot change openim ws port

### ISSUE THREAD

**Issue by AndrewZuo01** [openimsdk/openim-docker#68]
### What happened?

cannot change openim ws port, add friend fail

### What did you expect to happen?

can add friend

### How can we reproduce it (as minimally and precisely as possible)?

change openim ws port from 10001 to 40001 in .env, docker compose down, make clean, docker compose up -d
open port 11001 to access web front, register a user names asd, regsiter a user names dsa and add asd as friend, log in asd and cannot see dsa's friend request

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
@AndrewZuo01  Could you kindly provide additional details on the operational procedures? Your input will greatly enhance the clarity and comprehensiveness of the description.

**Comment by AndrewZuo01** [comment]
already updated

**Comment by cubxxw** [comment]
The environment variables were modified, and these changes were made after the initial startup.
